### ISSUE TITLE
JDK already existing on the Raspbian image.

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#10]
I installed a brand new Raspbian image and checked the `javac -version`, it showed `javac 1.8.0`.

Do we need some special file in the jdk at dropbox?

**Comment by cacyss0807** [comment]
I am not sure that the default `jdk` in Raspbian has JavaFX. Check by running only `java -Dcom.sun.javafx.transparentFramebuffer=true -jar DisplayMarquee.jar "Marquee text"`

**Comment by zeronone** [comment]
I installed your JDK now. It is okay :)

But I remember when I was testing JavaFX examples, I didn't download any
specific JDK (just used the system JDK).

**Comment by zeronone** [comment]
We can totally keep it. I am not sure if the system JDK has the JavaFX lib
included or not.

**Comment by cacyss0807** [comment]
@zeronone I rechecked and run the `DisplayMarquee.jar` without downloading any extra JDK and it works fine. Apparently, we can use the one that comes pre-installed. I will remove the (now) unnecessary JDK download from `setup` script. Refer to d846644403b0dd4ba6ad2813e76ee496866a5af6
