### ISSUE TITLE
Mouse appears on the screen.

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#14]
I guess it is due to JavaFX. 
The following guide shows how to disable mouse on raspberry pi using unclutter. http://harmoniccode.blogspot.jp/2014/02/fun-with-javafx-on-raspberry-pi-again.html

**Comment by cacyss0807** [comment]
Fixed by @zeronone using unclutter. refer to b775432a74b9538492dfdb60dc0cde8f5ca9ca77.
