### ISSUE TITLE
omxd error

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#20]
The line #108 in player.py `echo X > omxctl` will hang if there is no omxd reading it. That is FIFO if no one is reading it then it hangs. I commented out that part.

**Comment by cacyss0807** [comment]
I think I can just check if there is `omxctl` FIFO present, if so then send the command via `echo`

**Comment by zeronone** [comment]
No even if the file exists `echo ` will fail, since there is no reader of the file.

**Comment by cacyss0807** [comment]
Oh I see. I think I should comment line #123 but still line #108 is assuming `omxd` is already running so the FIFO file should exists. If it does not maybe there was an error setting up `omxd`. I will look into it.

**Comment by zeronone** [comment]
But mine hangs everytime at that line. Even when I start `python player.py` Probably because my previous omxd crashed and the ctrl files were still there.

**Comment by cacyss0807** [comment]
Fixed by @zeronone on this [branch](https://github.com/SNUArduinoLabs/coe_client/tree/use_omxd_daemon)
