### ISSUE TITLE
OMXD Daemon

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#22]
`omxd -d` is the debug version of the program. The original program is supposed to be `sudo omxd` and the control and log files will be at `/var/run/omxctl` and `/var/log/omxlog`. How about running omxd at the start of the raspberry pi. `init`

And while playing just `echo A ... > /var/run/omxctl` etc.

Restarting omxd and killing it causes a lot of problem. I guess it should be okay if one of the videos is played a little bit longer or a few minutes delay.

**Comment by cacyss0807** [comment]
Oh, I though `omxd` stands for `omx daemon`! :confused:. I will try to test that and update the necessary code. Gracias Santiago :+1:

**Comment by zeronone** [comment]
:+1:

**Comment by cacyss0807** [comment]
Fixed by @zeronone : b775432a74b9538492dfdb60dc0cde8f5ca9ca77
