### ISSUE TITLE
Editing same schedule does not have effect on the player

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_client#24]
If the currently being played schedule is X and we edit it and deploy it, no changes seem to take effect. This could be because player assumes that if it is the same player then it just sleeps.

**Comment by zeronone** [comment]
I guess it is my problem, i am not sending UPDATE request
I should have updated the server.

**Comment by zeronone** [comment]
It was kind of difficult, I had to change many places. Can you check if the current id for schedule exists. Then it is an update operation. Otherwise new. for now

**Comment by cacyss0807** [comment]
So if a schedule ID already exists I just delete it and save it again (like update would do), but it also allows new files to get updated

**Comment by zeronone** [comment]
new files? I didn't get it. There will be two cases for an update operation (ID already existing):
1. The schedule is currently running, stop and update
2. The schedule is currently not running: simply update

Is it okay?

**Comment by cacyss0807** [comment]
I see what you mean, okay I will do it like that :)

**Comment by zeronone** [comment]
:+1:

**Comment by cacyss0807** [comment]
@zeronone, I think you need to change nothing because it was working before without any change from the server side. If an schedule changes you just send me the same schedule with probably changed content files. Then, I check for the two cases you mentioned.

**Comment by cacyss0807** [comment]
Seems to be fixed: 9782bf41dcb1123cdb533437cd9f88f6f423e5c2
