### ISSUE TITLE
Black screen when playing a "IMAGE" and then a VIDEO

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_client#26]
The black screen does NOT disappear, however skipping to the next file in the omxd playlist (`echo n /var/run/omxctl` ) seems to correctly play the next file, then all the files in the playlist play correctly.

**Comment by zeronone** [comment]
and then reproduces? I didn't understand

**Comment by cacyss0807** [comment]
@zeronone I edited the previous post. So what I meant is that: after skipping to the next file, the play list plays correctly. Hope it makes sense :P

**Comment by cacyss0807** [comment]
Seems to be fixed. However, in case of any set of video and images that triggers this I will have a look again.
