### ISSUE TITLE
Player with JavaFX

### ISSUE THREAD

**Issue by zeronone** [SNUArduinoLabs/coe_client#3]
@cacyss0807 @mattmiranda Hey bros. Sorry I was away for few days. I didn't had internet these days. The plugs are all different. I will setup my internet today. 

I will try to do the Player with JavaFX. I will create a new pull request for the player. But for that I need to branch out from master. So please let me know if the master is stable. And the player is isolated from the rest of the project. I don't know how long it will take me to do it. So I will be merging very later on. So the player should be a separate process.

Last time calling the player from the server thread was causing a lot of problems. We should create a master supervisor process, whose sole purpose is launching the subprocessess (player, server and maybe downloader). So that later I can easily substitute my version of the player with yours. 

If the three processes are independent, a simple shell script should be enough for now (later on we can add supervision and failure functionalities). 

Please let me know what you guys decide to do, and whether the master branch is stable to branch out. I will then start working on the player. Meantime since all of us are far away now; I think it is a good idea to communicate our ideas through Gitub issues and Github pull requests.

**Comment by cacyss0807** [comment]
You can branch out from master. I think it is a good idea what you mention, I will review the current status and update futher ideas. So far the webserver is the main theead that starts the Downloader.

**Comment by zeronone** [comment]
@cacyss0807 Great!!! I will start as soon as I can
