### ISSUE TITLE
If `webserver` is stopped, it cannot be restarted

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_client#9]
If `supervisor` for any reason tries to restart `webserver` an exception is raised because the address is already in use. In such case, right now, the only solution is to reboot the RBpi :-1:

**Comment by zeronone** [comment]
What do you thing of the watchdog solution. The server keeps writing to a
file every two minutes. If there is no write in two minutes. Then restart
the whole RBPi

**Comment by cacyss0807** [comment]
Thank you for your idea :) that could be useful in case of unrecoverable errors.

However for now the supervisor handles any error and restarts it properly the problem is that apparently it does not kill all the group processes created by flask so there are orphans remaining that get attached to the port. Then,after a new instance is created and started by the supervisor  the web server generates an exception because the port is already being used. 

I saw a solution by killing all the process group or adding ngix on top of flask.

**Comment by zeronone** [comment]
How about putting the command: `fuser -k -n tcp 5000; python webserver.py`

**Comment by cacyss0807** [comment]
Fixed by @zeronone : 946a1e45b7ddf501f2df50a3609244fcabd6856a
